import javax.swing.*;
import java.awt.*;

public class Help extends JPanel {

   public Help() {
      String Airports[] = {"DEN (north america)",
         "DFW [north america]",
         "MCO [north america]",
         "IAD [north america]",
         "IAH [north america]",
         "SLC [north america]",
         "ORD [north america]",
         "SFO [north america]",
         "JFK [north america]",
         "DTW [north america]",
         "YYC [north america]",
         "YEG [north america]",
         "YUL [north america]",
         "YOW [north america]",
         "YYZ [north america]",
         "MEX [north america]",
         "CUN [north america]",
         "GDL [north america]",
         "HMO [north america]",
         "CZM [north america]",
         "GRU [south america]",
         "BOG [south america]",
         "SCL [south america]",
         "LIM [south america]",
         "GIG [south america]",
         "PTY [south america]",
         "AEP [south america]",
         "MUN [south america]",
         "CUZ [south america]",
         "COR [south america]",
         "IQT [south america]",
         "MVD [south america]",
         "UIO [south america]",
         "LPB [south america]",
         "ASU [south america]",
         "BSB [south america]",
         "CLO [south america]",
         "POA [south america]",
         "CTG [south america]",
         "CCS [south america]",
         "LHR [europe]",
         "CDG [europe]",
         "AMS [europe]",
         "FRA [europe]",
         "IST [europe]",
         "MAD [europe]",
         "BCN [europe]",
         "LGW [europe]",
         "MUC [europe]",
         "FCO [europe]",
         "SVO [europe]",
         "SAW [europe]",
         "DME [europe]",
         "DUB [europe]",
         "ZRH [europe]",
         "CPH [europe]",
         "PMI [europe]",
         "MAN [europe]",
         "OSL [europe]",
         "LIS [europe]",
         "ARN [europe]",
         "AYT [europe]",
         "STN [europe]",
         "BRU [europe]",
         "DUS [europe]",
         "VIE [europe]",
         "MXP [europe]",
         "ATH [europe]",
         "TXL [europe]",
         "HEL [europe]",
         "JNB [africa]",
         "CAI [africa]",
         "CPT [africa]",
         "CMN [africa]",
         "ADD [africa]",
         "ALG [africa]",
         "NBO [africa]",
         "LOS [africa]",
         "TUN [africa]",
         "DUR [africa]",
         "PEK [asia]",
         "DXB [asia]",
         "HND [asia]",
         "HKG [asia]",
         "DEL [asia]",
         "ICN [asia]",
         "CGK [asia]",
         "SIN [asia]",
         "BKK [asia]",
         "KUL [asia]",
         "TPE [asia]",
         "MNL [asia]",
         "JED [asia]",
         "SGN [asia]",
         "DOH [asia]",
         "SYD [oceania]",
         "MEL [oceania]",
         "AKL [oceania]",
         "NAN [oceania]",
         "POM [oceania]" };
      JComboBox cb = new JComboBox(Airports);
      cb.setMaximumRowCount(17);
      add(cb);  
      setBackground(new Color(0,181,226));
   
   }
}